In [1]:
# Import pandas
import pandas as pd

C:\Users\Admin\AppData\Local\Temp\ipykernel_19916\3422465919.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Create a DataFrame with balance.txt
df = pd.read_csv("balance.txt", sep = " " )  #delim_whitespace=True)

In [3]:
df.head()

,Balance,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity
0,12.240798,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian
1,23.283334,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian
2,22.530409,104.593,7075,514,4,71,11,Male,No,No,Asian
3,27.652811,148.924,9504,681,3,36,11,Female,No,No,Asian
4,16.893978,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian

* Compare the average income based on ethnicity.

In [4]:
# first lets know how many unique in ethnicity 
group = df.loc[:,"Ethnicity"].unique()
print(group)

['Caucasian' 'Asian' 'African American']

In [5]:

print("The average income based on ethnicity is", df[df.Ethnicity =="Caucasian"].loc[:,"Income"].mean())
print("The average income based on ethnicity is", df[df.Ethnicity =="Asian"].loc[:,"Income"].mean())
print("The average income based on ethnicity is", df[df.Ethnicity =="African American"].loc[:,"Income"].mean())

The average income based on ethnicity is 44.521944723618084
The average income based on ethnicity is 44.18783333333334
The average income based on ethnicity is 47.68210101010099

In [6]:
ave_income = round(df.groupby('Ethnicity')['Income'].mean(), 2)
print(ave_income)

Ethnicity
African American    47.68
Asian               44.19
Caucasian           44.52
Name: Income, dtype: float64

* On average, do married or single people have a higher balance?

In [7]:
print("The average income of married based in our dataframe is", df[df.Married =="Yes"].loc[:,"Balance"].mean())
print("The average income of unmarried based in our dataframe is", df[df.Married =="No"].loc[:,"Balance"].mean())

print("Our output shows that unmarried people have a little bit of higher balance.")

The average income of married based in our dataframe is 13.388473477498913
The average income of unmarried based in our dataframe is 13.493509015134242
Our output shows that unmarried people have a little bit of higher balance.

In [8]:
average_balance_by_marital_status = df.groupby('Married')['Balance'].mean()
print("The average balance for married people is:", average_balance_by_marital_status['Yes'])
print("The average balance for single people is:", average_balance_by_marital_status['No'])

The average balance for married people is: 13.388473477498913
The average balance for single people is: 13.493509015134242

In [9]:
df.groupby('Married')['Balance'].mean("Yes")

Married
No     13.493509
Yes    13.388473
Name: Balance, dtype: float64

* What is the highest income in our dataset?

In [10]:
print("The highest income in our dataset is", df.loc[:, "Income"].max())

The highest income in our dataset is 186.634

In [11]:
print("The highest income in our dataset is:", df['Income'].max())

The highest income in our dataset is: 186.634

* What is the lowest income in our dataset?

In [12]:
print("The lowest income in our dataset is", df.loc[:, "Income"].min())

The lowest income in our dataset is 10.354

In [13]:
print("The lowest income in our dataset is:", df['Income'].min())

The lowest income in our dataset is: 10.354

* How many cards do we have recorded in our dataset? (Hint: use `sum()`)

In [14]:
# using .iloc function
print("The numbers of card in my data base is", df.iloc[:,4].sum())

The numbers of card in my data base is 1183

* How many females do we have information for vs how many males?

In [15]:
print("The Numbers of females we have their informations is", df["Gender"].value_counts()["Female"])
print("The Numbers of Males we have their informations is", df["Gender"].value_counts()["Male"])

The Numbers of females we have their informations is 207
The Numbers of Males we have their informations is 193

Write the code needed to produce a report that provides the following information:
* Compare the average income based on ethnicity.
* On average, do married or single people have a higher balance?
* What is the highest income in our dataset?
* What is the lowest income in our dataset?
* How many cards do we have recorded in our dataset? (Hint: use `sum()`)
* How many females do we have information for vs how many males? (Hint: use `count()` for a list of all methods for computation of descriptive stats, explore the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).